#!/bin/sh

export VERSION=$(cat $2/version | tr -d '[:space:]')

curl -L https://busybox.net/downloads/busybox-${VERSION}.tar.bz2
tar -xf busybox-${VERSION}.tar.bz2

cd busybox-${VERSION}

# build the binary 
make defconfig
make
make CONFIG_PREFIX="$1/usr" install

cd ..

# create the actual symlinks for the programs
"$1/usr/bin/busybox" --list | while read -r bin; do
    ln -s busybox "$1/usr/bin/$bin"
done
